onlyBuiltDependencies:
  - '@ladybugdb/core'
  - '@scarf/scarf'
  - esbuild
  - onnxruntime-node
  - protobufjs
  - sharp
  - tree-sitter
  - tree-sitter-c
  - tree-sitter-c-sharp
  - tree-sitter-cli
  - tree-sitter-cpp
  - tree-sitter-dart
  - tree-sitter-go
  - tree-sitter-java
  - tree-sitter-javascript
  - tree-sitter-kotlin
  - tree-sitter-php
  - tree-sitter-python
  - tree-sitter-ruby
  - tree-sitter-rust
  - tree-sitter-swift
  - tree-sitter-typescript
